// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import routeProps from './routeProps';

if (process.env.NODE_ENV === 'development') {
  Object.entries(routeProps).forEach(([key, value]) => {
    const internalProps = ['path', 'id', 'parentId', 'isLayout', 'isWrapper', 'layout', 'clientLoader'];
    Object.keys(value).forEach((prop) => {
      if (internalProps.includes(prop)) {
        throw new Error(
          `[UmiJS] route '${key}' should not have '${prop}' prop, please remove this property in 'routeProps'.`
        )
      }
    })
  })
}

import React from 'react';

export async function getRoutes() {
  const routes = {"bar/index":{"path":"bar","id":"bar/index"},"foo/index":{"path":"foo","id":"foo/index"}} as const;
  return {
    routes,
    routeComponents: {
'bar/index': React.lazy(() => import(/* webpackChunkName: "src__pages__bar__index" */'../../../src/pages/bar/index.tsx')),
'foo/index': React.lazy(() => import(/* webpackChunkName: "src__pages__foo__index" */'../../../src/pages/foo/index.tsx')),
},
  };
}
