// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';
import ReactDOM from 'react-dom/client';
import App from 'E:/myProject/react-h5-pages/src/pages/bar/index.tsx';
import Layout from '@/layouts/basic';
ReactDOM.createRoot(document.getElementById('main')).render(<Layout><App /></Layout>);
